/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author firer
 */
public class Game extends javax.swing.JFrame {

    private gamePanel game;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        mainMenuJPanel = new javax.swing.JPanel();
        newGameJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valueJSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        partieJMenu = new javax.swing.JMenu();
        newGamejMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Little game");
        setResizable(false);

        newGameJButton.setText("Nouvelle partie");
        newGameJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LE MEILLEUR JEU TROUVE SUR LES PUBS INSTA");

        valueJSpinner.setValue(15);
        valueJSpinner.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("Longueur de la partie");

        javax.swing.GroupLayout mainMenuJPanelLayout = new javax.swing.GroupLayout(mainMenuJPanel);
        mainMenuJPanel.setLayout(mainMenuJPanelLayout);
        mainMenuJPanelLayout.setHorizontalGroup(
                mainMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainMenuJPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuJPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainMenuJPanelLayout.createSequentialGroup()
                                                .addGap(172, 172, 172)
                                                .addComponent(newGameJButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mainMenuJPanelLayout.createSequentialGroup()
                                                .addGap(216, 216, 216)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(valueJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(156, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                mainMenuJPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115)));
        mainMenuJPanelLayout.setVerticalGroup(
                mainMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                mainMenuJPanelLayout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addGroup(mainMenuJPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(valueJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2))
                                        .addGap(77, 77, 77)
                                        .addComponent(newGameJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(179, Short.MAX_VALUE)));

        partieJMenu.setText("Partie");
        partieJMenu.setEnabled(false);

        newGamejMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newGamejMenuItem.setText("Lancer nouvelle game");
        newGamejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGamejMenuItemActionPerformed(evt);
            }
        });
        partieJMenu.add(newGamejMenuItem);

        jMenuBar1.add(partieJMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainMenuJPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainMenuJPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void newGame() {
        remove(game);
        add(mainMenuJPanel);
        partieJMenu.setEnabled(false);
        revalidate();
        repaint();
    }

    private void newGamejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newGamejMenuItemActionPerformed
        remove(game);
        add(mainMenuJPanel);
        revalidate();
        repaint();
    }// GEN-LAST:event_newGamejMenuItemActionPerformed

    private void newGameJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newGameJButtonActionPerformed
        game = new gamePanel(this, Integer.valueOf(valueJSpinner.getValue().toString()).intValue());
        game.setSize(getWidth(), getHeight());
        remove(mainMenuJPanel);
        game.initGame();
        add(game);
        game.requestFocusInWindow();
        revalidate();
        repaint();
        partieJMenu.setEnabled(true);

    }// GEN-LAST:event_newGameJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel mainMenuJPanel;
    private javax.swing.JButton newGameJButton;
    private javax.swing.JMenuItem newGamejMenuItem;
    private javax.swing.JMenu partieJMenu;
    private javax.swing.JSpinner valueJSpinner;
    // End of variables declaration//GEN-END:variables
}
